[build]
  # El directorio donde Netlify debe pararse a trabajar
  base = "plataforma-iot-sanik/frontend"

  # El comando para compilar tu proyecto
  command = "npm run build"

  # La carpeta que se va a publicar (relativa a la carpeta 'base' de arriba)
  # Si usas Vite/Vue/Svelte suele ser "dist". Si usas React puro suele ser "build".
  publish = "dist"

[functions]
  # Si tienes funciones de Netlify dentro de tu frontend
  directory = "netlify/functions"